# Generated by Django 4.2.6 on 2023-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'PRODUCT_MASTER',
            },
        ),
    ]
